name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client netcat-openbsd
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up SSH tunnel
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
          ssh -fN -p ${{ secrets.SSH_PORT || '22' }} -L 27017:localhost:27017 ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_SERVER }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Set up environment file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
          chmod 600 .env
          
      - name: Run data collection
        env:
          MONGO_HOST: ${{ env.MONGO_HOST }}
          MONGO_PORT: ${{ env.MONGO_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
        run: |
          python arxiv_collector.py --max=5 --keep-existing
      
      - name: Generate visualization
        env:
          MONGO_HOST: ${{ env.MONGO_HOST }}
          MONGO_PORT: ${{ env.MONGO_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
        run: |
          python arxiv_visualizer.py --no-browser
      
      - name: Prepare GitHub Pages content
        run: |
          # Create the GitHub Pages directory
          mkdir -p gh-pages
          # Copy the renders directory (contains main.html, list.html, and all visualizations)
          cp -r renders/* gh-pages/
          # Rename main.html to index.html for GitHub Pages
          mv gh-pages/main.html gh-pages/index.html
          # Update links in all HTML files to reference index.html instead of main.html
          find gh-pages -name "*.html" -exec sed -i 's/main\.html/index.html/g' {} \;
          # Create a README for the GitHub Pages branch
          echo "# ArXiv AI Security Papers" > gh-pages/README.md
          echo "Generated by GitHub Actions on $(date)" >> gh-pages/README.md
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
          # The branch the action should deploy to
          branch: gh-pages
      
      - name: Clean up SSH tunnel
        if: always()  # Run even if previous steps fail
        run: |
          # Kill any SSH processes
          pkill -f "ssh -fN -L" || true
          
          # Kill SSH agents
          if [ -f ~/ssh_agent_pid.txt ]; then
            kill $(cat ~/ssh_agent_pid.txt) || true
            rm ~/ssh_agent_pid.txt
          fi
